name: CI Pipeline

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Python Lint (flake8)
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Docker Lint (hadolint)
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: api/Dockerfile

      - name: Run Pytest
        run: |
          pip install -r api/requirements.txt pytest pytest-cov
          export REDIS_HOST=localhost
          pytest --cov=. --cov-report=xml

      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage.xml

      - name: Security Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'api-test:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '0' # Change to 1 to fail on critical later

      - name: Build and Compose Check
        run: |
          docker compose build
          docker compose up -d
          docker compose ps
          docker compose down